### ISSUE TITLE
Add a Licence

### ISSUE THREAD

**Issue by harens** [sapieninja/TraceRoute#1]
As of the time of writing, there is currently [no license](https://choosealicense.com/no-permission/) present:

> Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation.

_(Congrats on the great start to the project by the way. Looking forward to seeing where it goes 👍)_

**Comment by zeevox** [comment]
Thank you for starting this discussion, Haren. 

Licensing is going to be less straightforward when taking libraries used into consideration. Since we are probably going to be using [this OSM parsing library](https://github.com/woltapp/parallelpbf) GPLv3 seems like a necessary choice. However the program will also be [altering and building upon OpenStreetMap data](https://www.openstreetmap.org/copyright) which is provided under [ODbL](https://opendatacommons.org/licenses/odbl/). 

I think that it will be easier to make a call once the project is nearing completion and we have a clearer picture of our licensing obligations.

**Comment by sapieninja** [comment]
I agree with timothy in that we should wait until we have finished (or at least made something) because at the moment we currently have a 2 minute python script, an empty java project and some LaTeX, so it is unlikely anybody will want to copy, distribute or modify our project.
